## Python Exceptions

This is a project on Exception in python. Exceptions in python occurs when there is a disruption during the execution of a program instructions.

```
result of my_div: 5.0
Traceback (most recent call last):
  File "./test.py", line 12, in <module>
    result = safe_function(my_div, 10, 0)
  File "/home/useradd/alx-higher_level_programming/0x05-python-exceptions/101-safe_function.py", line 5, in safe_function
    cont = fct(*args)
  File "./test.py", line 6, in my_div
    return a / b
ZeroDivisionError: division by zero

```

An exception occured during the execution of a program instruction resulting to the output above.

## Files in the Directory

The files below contains programming instructions that solves the given tasks in the project.

#### 0-safe_print_list.py
